#!/system/bin/sh
# CPU governor tweaks For Fly-On Mod™ by Slaid480!

#============ Copyright (C) 2015 Salah Abouabdallah(Slaid480)===========#
 
 see <http://www.gnu.org/licenses/>.
 
#=======================================================================#

FLY=/data/Fly-On/23Booster.log

busybox rm -f $FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" )  Enabling Booster (Balanced) mode please wait..." | tee -a $FLY;

# Setting CPU governor to Ondemand

echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor


# Tweaking the governor

  if [ -e /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold ]; then
    echo "80" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate;
	
  fi;
  if [ -e /sys/devices/system/cpu/cpu1/cpufreq/ondemand/up_threshold ]; then

    echo "80" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu1/cpufreq/ondemand/sampling_rate;

  fi;
  if [ -e /sys/devices/system/cpu/cpu2/cpufreq/ondemand/up_threshold ]; then

    echo "80" > /sys/devices/system/cpu/cpu2/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu2/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu2/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu2/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu2/cpufreq/ondemand/sampling_rate;

  fi;  
  if [ -e /sys/devices/system/cpu/cpu3/cpufreq/ondemand/up_threshold ]; then

    echo "80" > /sys/devices/system/cpu/cpu3/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu3/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu3/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu3/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu3/cpufreq/ondemand/sampling_rate;

  fi;
  if [ -e /sys/devices/system/cpu/cpu4/cpufreq/ondemand/up_threshold ]; then
    echo "80" > /sys/devices/system/cpu/cpu4/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu4/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu4/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu4/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu4/cpufreq/ondemand/sampling_rate;
	
  fi;
  if [ -e /sys/devices/system/cpu/cpu5/cpufreq/ondemand/up_threshold ]; then
    echo "80" > /sys/devices/system/cpu/cpu5/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu5/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu5/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu5/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu5/cpufreq/ondemand/sampling_rate;
	
  fi;
  if [ -e /sys/devices/system/cpu/cpu6/cpufreq/ondemand/up_threshold ]; then
    echo "80" > /sys/devices/system/cpu/cpu6/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu6/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu6/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu6/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu6/cpufreq/ondemand/sampling_rate;
	
  fi;
  if [ -e /sys/devices/system/cpu/cpu7/cpufreq/ondemand/up_threshold ]; then
    echo "80" > /sys/devices/system/cpu/cpu7/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpu7/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpu7/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpu7/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpu7/cpufreq/ondemand/sampling_rate;
	
  fi;
  if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ]; then

    echo "80" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold;
    echo "15" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential;
    echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy;
    echo "2" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor;
    echo "30000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate;
  fi;


  
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Booster (Balanced) Mode is Enabled, enjoy !" | tee -a $FLY;
